// Copied from haushalts-todos (mcp/oauthRoutes.ts), adapted for xitl ADR-0012 /
// ADR-0014. Discovery metadata + Dynamic Client Registration + the
// authorization-code-with-PKCE flow for the MCP OAuth authorization server:
// every client is bound to the approving user. Differences from Haushalt: the
// protected resource is per upstream (`/mcp/<slug>`), so there is a
// path-aware protected-resource document per slug.
// `/oauth/authorize` (consent, GET+POST — deliberately off the `/mcp` prefix,
// see AUTHORIZE_PATH below) and `/mcp/token` (the grant endpoint) are the two
// endpoints that actually move a client from "has a client_id" to "has an
// access token". Note in particular the ordering rule in `GET
// /oauth/authorize` that avoids an open redirect and the stateless-code
// single-use caveat.
//
// Every artefact minted here goes through `lib/mcpOAuth.ts` (the signed-blob
// crypto core); this file is pure HTTP shaping on top of that, plus the
// SDK's own Zod schemas (`@modelcontextprotocol/core`, a direct dependency
// so importing them isn't reaching into an undeclared transitive package)
// to catch a shape mistake here rather than in a client's face. The SDK also
// ships ready-made `buildOAuthProtectedResourceMetadata`/
// `oauthMetadataResponse` helpers, but their protected-resource output omits
// `bearer_methods_supported` (which the app's own consumers — and RFC 9728
// clients generally — expect), so the metadata objects are built by hand
// here and validated against the schemas instead of generated by those
// helpers.
import crypto from 'node:crypto';
import type { Context, Hono } from 'hono';
import { getCookie, setCookie } from 'hono/cookie';
import {
  OAuthClientInformationFullSchema,
  OAuthClientMetadataSchema,
  OAuthMetadataSchema,
  OAuthProtectedResourceMetadataSchema,
  OAuthTokensSchema,
} from '@modelcontextprotocol/core';
import { getOAuthProtectedResourceMetadataUrl } from '@modelcontextprotocol/server';
import {
  ACCESS_TTL,
  issueAccessToken,
  issueAuthCode,
  issueRefreshToken,
  timingSafeEqualStr,
  verifyBlob,
  verifyPkceS256,
  type CodeClaims,
  type RefreshClaims,
} from '../lib/mcpOAuth.js';
import { externalOrigin } from '../lib/externalOrigin.js';
import { isUpstreamSlug } from '../lib/slugs.js';
import { prisma } from '../db.js';
import { identity, type AppEnv } from '../identity.js';

// The consent flow's authorization endpoint lives at **`/oauth/authorize`**, NOT
// under `/mcp/*` like the other OAuth endpoints.
//
// It HAS to be off the `/mcp` prefix: the machine-to-machine endpoints (`/mcp`,
// `/mcp/register`, `/mcp/token`, the well-knowns) are exempt from Authelia so a
// client with no session can reach them — but the consent page MUST stay
// *behind* Authelia, because that ForwardAuth login is the only thing proving
// it's Matthias clicking "Erlauben" and not an anonymous stranger. If it lived
// at `/mcp/authorize`, a `/mcp`-prefix exemption would expose it too and the
// whole flow would authenticate nobody. Off the prefix, the ingress exempts
// `/mcp` cleanly and this stays protected by default.
//
// `/oauth/authorize` rather than a bare `/authorize`: purely tidiness — it
// namespaces the OAuth surface instead of squatting a top-level path. A
// compliant client reads `authorization_endpoint` out of the AS metadata (which
// advertises exactly this path) and follows it there. (A brief earlier build
// used `/authorize` after the connector was seen going there — but that was its
// *fallback when discovery failed*, i.e. while the `/.well-known/oauth-*` docs
// were still behind Authelia and unreadable; with those exempted, the connector
// follows the advertised path and the tidier one is free to use.)
const AUTHORIZE_PATH = '/oauth/authorize';

// xitl has several users (ADR-0010), so "behind Authelia" is not enough: the consent page
// must know WHO approves, because that user gets bound to the client and to
// every token issued for it (ADR-0012). `identity` (the same middleware as on
// /api/*) is mounted on this path in mountMcpOAuth: no `Remote-User` -> 401, and
// the handlers below read `c.get('user')`. Fail closed: a handler that finds no
// user answers 401 even if the middleware were ever removed.

// Double-submit CSRF token for the consent POST. `/oauth/authorize`
// is behind Authelia, whose session cookie is the first line of defence
// (a cross-site POST won't carry a SameSite=Lax/Strict cookie), but that's the
// operator's config, not ours — this is the belt to that suspenders, entirely
// within the app. GET sets a random value as a SameSite=Strict cookie AND
// renders it in a hidden field; POST requires the two to match. A forged
// cross-site POST can neither read the cookie nor make the browser send it, so
// it can't produce a matching field.
const CSRF_COOKIE = 'mcp_oauth_csrf';

// The RFC 9728 well-known path for this server's `/mcp` resource, derived
// from the SDK's own path-building logic rather than hardcoded a second
// time — mount.ts's `resourceMetadataUrl` (the 401 challenge's
// `resource_metadata`) is built from the same helper, so the two can't drift
// apart. Only the *path* is used; the placeholder origin below never
// appears in a response. The per-upstream form (`/mcp/<slug>`, ADR-0014) is
// `${PROTECTED_RESOURCE_PATH}/<slug>`; the SDK helper yields exactly that for
// `/mcp/<slug>` (asserted in the e2e TC-10), so the route below uses the same
// prefix.
const PROTECTED_RESOURCE_PATH = new URL(
  getOAuthProtectedResourceMetadataUrl(new URL('http://placeholder.invalid/mcp')),
).pathname;

const WELL_KNOWN_HEADERS = { 'Cache-Control': 'public, max-age=300' };
const NO_STORE_HEADERS = { 'Cache-Control': 'no-store' };

/** RFC 7591 §3.2.2: a redirect_uri must be an absolute, unparseable-proof
 * URL. `https://` for anything real; `http://` is accepted only for
 * localhost/127.0.0.1, the shape a local CLI client registers with while
 * it's doing its own loopback redirect. */
function isAllowedRedirectUri(raw: string): boolean {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return false;
  }
  if (url.protocol === 'https:') return true;
  return url.protocol === 'http:' && (url.hostname === 'localhost' || url.hostname === '127.0.0.1');
}

/** Minimal HTML-escaping for values interpolated into the consent/error
 * pages below. Everything embedded there — `client_name` from a DCR
 * registration, `redirect_uri`/`state`/`code_challenge`/`scope` off the
 * query string or form body — is attacker-influenced, so this isn't
 * decorative: an unescaped `client_name` or `state` is a stored/reflected
 * XSS in a page that's about to ask the user to click "Erlauben". */
function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const PAGE_STYLE = `
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px 16px;
    background: #faf9f7;
    color: #1f2933;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }
  .card {
    width: 100%;
    max-width: 420px;
    background: #fff;
    border: 1px solid #e6e1d8;
    border-radius: 12px;
    padding: 24px 20px;
  }
  h1 { font-size: 1.15rem; margin: 0 0 12px; }
  p { line-height: 1.5; margin: 0 0 8px; }
  .muted { color: #5b6672; font-size: 0.9rem; }
  .actions { display: flex; gap: 12px; margin-top: 24px; }
  button {
    flex: 1;
    padding: 14px 16px;
    font-size: 1rem;
    font-weight: 600;
    border-radius: 8px;
    border: 1px solid transparent;
    cursor: pointer;
  }
  .allow { background: #b4531f; color: #fff; }
  .deny { background: transparent; color: #1f2933; border-color: #c7bfae; }
  label { display: block; font-size: 0.9rem; margin: 16px 0 6px; }
  input[type="text"] {
    width: 100%;
    padding: 10px 12px;
    font-size: 1rem;
    border-radius: 8px;
    border: 1px solid #c7bfae;
    background: #fff;
    color: #1f2933;
  }
  @media (prefers-color-scheme: dark) {
    body { background: #1f2933; color: #f4f1ec; }
    .card { background: #2b3542; border-color: #3d4a59; }
    .muted { color: #a9b4c0; }
    .deny { color: #f4f1ec; border-color: #4d5966; }
    input[type="text"] { background: #1f2933; color: #f4f1ec; border-color: #4d5966; }
  }
`;

function htmlPage(title: string, bodyHtml: string): string {
  return `<!doctype html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>${PAGE_STYLE}</style>
</head>
<body>
<div class="card">
${bodyHtml}
</div>
</body>
</html>`;
}

/** Rendered for the two failures in `GET /oauth/authorize` that happen
 * *before* `redirect_uri` is trusted — an unknown/invalid
 * `client_id`, or a `redirect_uri` that doesn't exactly match the client's
 * registration. Both must **not** redirect: redirecting to an unvalidated
 * URI is exactly the open-redirect hole this ordering exists to close. */
function renderErrorPage(message: string): string {
  return htmlPage(
    'Fehler – xitl',
    `<h1>Anfrage kann nicht verarbeitet werden</h1>
<p>${escapeHtml(message)}</p>`,
  );
}

const BOUND_MESSAGE =
  'Dieser Zugriff gehört bereits zu einer anderen Person und kann nicht von dir freigegeben werden. ' +
  'Richte in Claude einen eigenen Konnektor für dich ein.';

function renderConsentPage(params: {
  clientName: string;
  userName: string;
  clientId: string;
  redirectUri: string;
  codeChallenge: string;
  scope: string;
  state: string;
  csrf: string;
}): string {
  const name = params.clientName || 'Ein MCP-Client';
  return htmlPage(
    'Zugriff erlauben – xitl',
    `<h1>${escapeHtml(name)} möchte über xitl auf deine Upstreams zugreifen</h1>
<p>Du bist angemeldet als <strong>${escapeHtml(params.userName)}</strong>. Alles, was dieser
Zugriff tut, läuft unter deinem Namen und nach deinen Regeln.</p>
<p class="muted">Du kannst ihn jederzeit in den Einstellungen trennen.</p>
<form method="POST" action="${AUTHORIZE_PATH}">
  <input type="hidden" name="client_id" value="${escapeHtml(params.clientId)}">
  <input type="hidden" name="redirect_uri" value="${escapeHtml(params.redirectUri)}">
  <input type="hidden" name="code_challenge" value="${escapeHtml(params.codeChallenge)}">
  <input type="hidden" name="scope" value="${escapeHtml(params.scope)}">
  <input type="hidden" name="state" value="${escapeHtml(params.state)}">
  <input type="hidden" name="csrf" value="${escapeHtml(params.csrf)}">
  <label for="client_name">Name für diesen Zugriff</label>
  <input type="text" id="client_name" name="client_name" value="${escapeHtml(name)}">
  <div class="actions">
    <button type="submit" name="decision" value="deny" class="deny">Ablehnen</button>
    <button type="submit" name="decision" value="allow" class="allow">Erlauben</button>
  </div>
</form>`,
  );
}

/** Appends query params to a redirect_uri that's already been validated as
 * an exact match against the client's registration — never called on an
 * unvalidated URI. `undefined` values are omitted (e.g. an absent `state`,
 * which OAuth clients aren't required to send). */
function appendQuery(base: string, params: Record<string, string | undefined>): string {
  const url = new URL(base);
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) url.searchParams.set(key, value);
  }
  return url.toString();
}

/** A form/query field, coerced to a string or '' — Hono's `parseBody` can
 * hand back a `File` for a same-named multipart field, which none of these
 * params legitimately are. */
function field(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function tokenError(c: Context, error: string, error_description: string) {
  return c.json({ error, error_description }, 400, NO_STORE_HEADERS);
}

/** Bumps a client's `lastUsedAt` on a successful token issuance — the "last
 * active" signal a later Settings list will show. Best-effort on purpose:
 * revocation doesn't exist yet in this slice, so a row vanishing between
 * `/authorize` and here isn't a real scenario today, but nothing about this
 * update is worth failing the actual token response over even so. */
async function bumpLastUsed(clientId: string): Promise<void> {
  try {
    await prisma.mcpClient.update({ where: { clientId }, data: { lastUsedAt: new Date() } });
  } catch {
    // Client row gone (or some other update failure) — token issuance still
    // proceeds; this is a nice-to-have signal, not a correctness dependency.
  }
}

/** Sets the double-submit CSRF cookie for the consent flow. `SameSite=Strict`
 * so a cross-site POST never carries it; `HttpOnly` since only the server
 * needs it (it's echoed into a hidden field server-side, never read by JS);
 * scoped to the authorize path; `Secure` only over https, so the e2e/local
 * http flow (where the cookie must still round-trip) isn't silently dropped. */
function setCsrfCookie(c: Context, value: string): void {
  setCookie(c, CSRF_COOKIE, value, {
    httpOnly: true,
    sameSite: 'Strict',
    path: AUTHORIZE_PATH,
    maxAge: 600,
    secure: externalOrigin(c).startsWith('https://'),
  });
}

export function mountMcpOAuth(app: Hono<AppEnv>, secret: string): void {
  // Identity gate for the consent page (GET and POST). Registered before the
  // handlers below; Hono runs middleware in registration order.
  app.use(AUTHORIZE_PATH, identity);

  app.get('/.well-known/oauth-authorization-server', (c) => {
    const origin = externalOrigin(c);
    const metadata = OAuthMetadataSchema.parse({
      issuer: origin,
      authorization_endpoint: `${origin}${AUTHORIZE_PATH}`,
      token_endpoint: `${origin}/mcp/token`,
      registration_endpoint: `${origin}/mcp/register`,
      response_types_supported: ['code'],
      grant_types_supported: ['authorization_code', 'refresh_token'],
      code_challenge_methods_supported: ['S256'],
      token_endpoint_auth_methods_supported: ['none'],
      scopes_supported: ['mcp'],
    });
    return c.json(metadata, 200, WELL_KNOWN_HEADERS);
  });

  const protectedResourceHandler = (c: Context, resourcePath = '/mcp') => {
    const origin = externalOrigin(c);
    const metadata = OAuthProtectedResourceMetadataSchema.parse({
      resource: `${origin}${resourcePath}`,
      authorization_servers: [origin],
      scopes_supported: ['mcp'],
      bearer_methods_supported: ['header'],
    });
    return c.json(metadata, 200, WELL_KNOWN_HEADERS);
  };
  // Both the bare well-known (some clients probe it without the resource
  // path) and the path-aware one the SDK's `requireBearerAuth` challenge
  // actually points at (mount.ts) — same document either way.
  app.get('/.well-known/oauth-protected-resource', (c) => protectedResourceHandler(c));
  app.get(PROTECTED_RESOURCE_PATH, (c) => protectedResourceHandler(c));
  // Per upstream (ADR-0014): `resource` is that upstream's own endpoint. The slug
  // is echoed into the document, so it must pass the slug pattern first. The
  // document is public and says nothing about whether the slug exists.
  app.get(`${PROTECTED_RESOURCE_PATH}/:slug`, (c) => {
    const slug = c.req.param('slug');
    if (!isUpstreamSlug(slug)) return c.json({ error: 'Not found' }, 404);
    return protectedResourceHandler(c, `/mcp/${slug}`);
  });

  app.post('/mcp/register', async (c) => {
    let body: unknown;
    try {
      body = await c.req.json();
    } catch {
      return c.json(
        { error: 'invalid_client_metadata', error_description: 'Request body must be JSON.' },
        400,
        NO_STORE_HEADERS,
      );
    }

    const parsed = OAuthClientMetadataSchema.safeParse(body);
    if (!parsed.success) {
      return c.json(
        {
          error: 'invalid_client_metadata',
          error_description: 'redirect_uris is required and must be a list of absolute URLs.',
        },
        400,
        NO_STORE_HEADERS,
      );
    }

    const { redirect_uris, client_name, grant_types, response_types } = parsed.data;
    if (redirect_uris.length === 0 || !redirect_uris.every(isAllowedRedirectUri)) {
      return c.json(
        {
          error: 'invalid_redirect_uri',
          error_description:
            'redirect_uris must be a non-empty list of absolute https:// URLs (http:// only for localhost/127.0.0.1).',
        },
        400,
        NO_STORE_HEADERS,
      );
    }

    // The client itself is now a DB row (Settings lists and revokes
    // clients individually) — only the
    // client is persisted, tokens/codes stay signed blobs below. An opaque
    // random id, not a signed blob: nothing about it needs to be
    // self-verifying, the row is the source of truth.
    const client_id = crypto.randomBytes(24).toString('base64url');
    const name = client_name?.trim() ? client_name.trim() : 'Unbenannter Client';
    await prisma.mcpClient.create({
      data: { clientId: client_id, kind: 'OAUTH', name, redirectUris: JSON.stringify(redirect_uris) },
    });

    const registration = OAuthClientInformationFullSchema.parse({
      client_id,
      client_id_issued_at: Math.floor(Date.now() / 1000),
      redirect_uris,
      token_endpoint_auth_method: 'none', // public client — PKCE only, no client_secret
      grant_types: grant_types ?? ['authorization_code', 'refresh_token'],
      response_types: response_types ?? ['code'],
      ...(client_name ? { client_name } : {}),
    });
    return c.json(registration, 201, NO_STORE_HEADERS);
  });

  // --- GET /oauth/authorize — the consent page ------------------------------
  //
  // In production this sits *behind* Authelia (unlike every other endpoint
  // in this file) — the ingress gates it, and that ForwardAuth challenge is
  // the user login this flow relies on. This handler only ever runs for a
  // request Authelia already let through, so it has no identity/password
  // concept of its own; the consent decision below expresses authorization,
  // not authentication.
  //
  // Validation order matters and is deliberate (from Haushalt's ADR-0024): `client_id` and
  // `redirect_uri` are checked *before* anything else, and a failure of
  // either renders an error page instead of redirecting anywhere — a
  // redirect to an unvalidated URI is an open redirect. Only once
  // `redirect_uri` is a verified, exact member of the client's own
  // registration is it safe to use as an error-redirect target for
  // everything that follows.
  app.get(AUTHORIZE_PATH, async (c) => {
    const q = c.req.query();

    const clientId = q.client_id ?? '';
    const client = clientId ? await prisma.mcpClient.findUnique({ where: { clientId, kind: 'OAUTH' } }) : null;
    if (!client) {
      return c.html(renderErrorPage('Unbekannter oder abgelaufener client_id-Parameter.'), 400);
    }
    const redirectUris: string[] = JSON.parse(client.redirectUris);

    const redirectUri = q.redirect_uri ?? '';
    if (!redirectUris.includes(redirectUri)) {
      return c.html(
        renderErrorPage('redirect_uri stimmt nicht mit der Registrierung dieses Clients überein.'),
        400,
      );
    }

    const user = c.get('user');
    if (!user) return c.html(renderErrorPage('Nicht angemeldet.'), 401);
    // Already bound to someone else: refuse before showing a consent button.
    if (client.userId !== null && client.userId !== user.id) {
      return c.html(renderErrorPage(BOUND_MESSAGE), 403);
    }

    // redirect_uri is now trusted — every failure from here on redirects
    // back to it with an OAuth error, per spec, instead of showing a page.
    const state = q.state;

    if (q.response_type !== 'code') {
      return c.redirect(appendQuery(redirectUri, { error: 'unsupported_response_type', state }), 302);
    }

    if (!q.code_challenge || q.code_challenge_method !== 'S256') {
      // PKCE is mandatory and S256-only — `plain` is refused, matching what
      // the discovery metadata advertises (code_challenge_methods_supported).
      return c.redirect(appendQuery(redirectUri, { error: 'invalid_request', state }), 302);
    }

    const requestedScopes = q.scope ? q.scope.split(' ').filter(Boolean) : [];
    if (requestedScopes.some((s) => s !== 'mcp')) {
      return c.redirect(appendQuery(redirectUri, { error: 'invalid_scope', state }), 302);
    }

    const csrf = crypto.randomBytes(32).toString('base64url');
    setCsrfCookie(c, csrf);
    return c.html(
      renderConsentPage({
        clientName: client.name,
        userName: user.displayName,
        clientId,
        redirectUri,
        codeChallenge: q.code_challenge,
        scope: q.scope ?? '',
        state: state ?? '',
        csrf,
      }),
    );
  });

  // --- POST /oauth/authorize — the consent decision -------------------------
  //
  // Never trusts the GET handler's validation — this is its own request, and
  // could in principle arrive without a prior GET at all (a replayed/crafted
  // form post). `client_id` and the exact `redirect_uri` match are
  // re-verified from scratch before anything else, same reasoning and same
  // "error page, don't redirect" rule as the GET handler above.
  app.post(AUTHORIZE_PATH, async (c) => {
    const body = await c.req.parseBody().catch(() => null);
    if (!body) {
      return c.html(renderErrorPage('Das Formular konnte nicht gelesen werden.'), 400);
    }

    const clientId = field(body.client_id);
    const client = clientId ? await prisma.mcpClient.findUnique({ where: { clientId, kind: 'OAUTH' } }) : null;
    if (!client) {
      return c.html(renderErrorPage('Unbekannter oder abgelaufener client_id-Parameter.'), 400);
    }
    const redirectUris: string[] = JSON.parse(client.redirectUris);

    const redirectUri = field(body.redirect_uri);
    if (!redirectUris.includes(redirectUri)) {
      return c.html(
        renderErrorPage('redirect_uri stimmt nicht mit der Registrierung dieses Clients überein.'),
        400,
      );
    }

    // Double-submit CSRF check: the cookie set when the consent page was
    // rendered must match the hidden field posted back with it. A forged
    // cross-site POST has neither (the SameSite=Strict cookie isn't sent, and
    // the attacker can't read it to fill the field). Checked here rather than
    // redirected — a CSRF/stale post is not an OAuth error to hand back to the
    // client, it's a refusal to act at all.
    const cookieCsrf = getCookie(c, CSRF_COOKIE);
    const formCsrf = field(body.csrf);
    if (!cookieCsrf || !formCsrf || !timingSafeEqualStr(cookieCsrf, formCsrf)) {
      return c.html(
        renderErrorPage('Die Sitzung ist abgelaufen oder ungültig. Bitte starte den Vorgang neu.'),
        400,
      );
    }

    const user = c.get('user');
    if (!user) return c.html(renderErrorPage('Nicht angemeldet.'), 401);
    if (client.userId !== null && client.userId !== user.id) {
      return c.html(renderErrorPage(BOUND_MESSAGE), 403);
    }

    const state = field(body.state) || undefined;

    if (field(body.decision) !== 'allow') {
      return c.redirect(appendQuery(redirectUri, { error: 'access_denied', state }), 302);
    }

    // Approving is also the one place the editable name from the consent
    // page lands — an empty/absent submission keeps the existing name rather
    // than overwriting it with blank.
    const submittedName = field(body.client_name).trim();

    // Bind the client to the approving user (ADR-0012). One conditional UPDATE
    // so two concurrent approvals by different users can't both win: it only
    // matches a client that is still unbound or already bound to THIS user.
    // count 0 = bound to someone else in the meantime, or revoked.
    const bound = await prisma.mcpClient.updateMany({
      where: { clientId, kind: 'OAUTH', OR: [{ userId: null }, { userId: user.id }] },
      data: { userId: user.id, ...(submittedName ? { name: submittedName } : {}) },
    });
    if (bound.count === 0) {
      const now = await prisma.mcpClient.findUnique({ where: { clientId, kind: 'OAUTH' } });
      return now
        ? c.html(renderErrorPage(BOUND_MESSAGE), 403)
        : c.html(renderErrorPage('Unbekannter oder abgelaufener client_id-Parameter.'), 400);
    }

    const codeChallenge = field(body.code_challenge);
    const code = issueAuthCode({ cid: clientId, uid: user.id, redirect_uri: redirectUri, code_challenge: codeChallenge, scope: ['mcp'] }, secret);
    return c.redirect(appendQuery(redirectUri, { code, state }), 302);
  });

  // --- POST /mcp/token — the grant endpoint ----------------------------------
  //
  // Public, unlike /oauth/authorize — a client with a code or refresh token
  // reaches this directly with no Authelia session (it's not a browser
  // navigation). `token_endpoint_auth_method: none` in discovery means
  // there's no client_secret to check; the client is authenticated for the
  // authorization_code grant implicitly, by way of the PKCE verifier only
  // the party that started the flow could hold.
  //
  // Stateless single-use caveat: a signed code can't be marked
  // "used" without a server-side store, so within its 60s TTL a captured
  // code could in principle be redeemed twice. Accepted for a two-person
  // homelab given the short window, the PKCE binding (a replay needs the
  // original code_verifier, not just the code) and the exact redirect_uri
  // binding — not fixed with a store.
  app.post('/mcp/token', async (c) => {
    const body = await c.req.parseBody().catch(() => null);
    if (!body) return tokenError(c, 'invalid_request', 'Request body must be application/x-www-form-urlencoded.');

    const grantType = field(body.grant_type);

    if (grantType === 'authorization_code') {
      const code = field(body.code);
      const codeVerifier = field(body.code_verifier);
      const clientId = field(body.client_id);
      const redirectUri = field(body.redirect_uri);
      if (!code || !codeVerifier || !clientId || !redirectUri) {
        return tokenError(c, 'invalid_request', 'code, code_verifier, client_id and redirect_uri are all required.');
      }

      const claims = verifyBlob<CodeClaims>(code, 'code', secret);
      if (!claims) return tokenError(c, 'invalid_grant', 'The authorization code is invalid or expired.');
      if (clientId !== claims.cid) return tokenError(c, 'invalid_grant', 'client_id does not match the code.');
      if (redirectUri !== claims.redirect_uri) {
        return tokenError(c, 'invalid_grant', 'redirect_uri does not match the code.');
      }
      if (!verifyPkceS256(codeVerifier, claims.code_challenge)) {
        return tokenError(c, 'invalid_grant', 'code_verifier does not match the code_challenge.');
      }
      // Revoked since the code was issued (revoke = delete the
      // McpClient row) → refuse the mint outright, rather than handing back a
      // token that would just fail at the /mcp gate a moment later.
      const client = await prisma.mcpClient.findUnique({ where: { clientId: claims.cid, kind: 'OAUTH' } });
      if (!client) return tokenError(c, 'invalid_grant', 'This client has been revoked.');
      // The code's user must still be the client's bound user (ADR-0012).
      if (client.userId === null || client.userId !== claims.uid) {
        return tokenError(c, 'invalid_grant', 'This client is not bound to the approving user.');
      }

      const access_token = issueAccessToken({ cid: claims.cid, uid: claims.uid, scope: claims.scope }, secret);
      const refresh_token = issueRefreshToken({ cid: claims.cid, uid: claims.uid, scope: claims.scope }, secret);
      // "Last active" for a later Settings list — best-effort: the client row
      // could in principle have vanished between /authorize and here (no
      // revocation exists yet to cause that, but nothing stops it becoming
      // true later), and that must never fail token issuance itself.
      await bumpLastUsed(claims.cid);
      const tokens = OAuthTokensSchema.parse({
        access_token,
        token_type: 'Bearer',
        expires_in: ACCESS_TTL,
        scope: claims.scope.join(' '),
        refresh_token,
      });
      return c.json(tokens, 200, NO_STORE_HEADERS);
    }

    if (grantType === 'refresh_token') {
      const refreshToken = field(body.refresh_token);
      const clientId = field(body.client_id);
      if (!refreshToken || !clientId) {
        return tokenError(c, 'invalid_request', 'refresh_token and client_id are required.');
      }

      const claims = verifyBlob<RefreshClaims>(refreshToken, 'refresh', secret);
      if (!claims) return tokenError(c, 'invalid_grant', 'The refresh token is invalid or expired.');
      if (clientId !== claims.cid) return tokenError(c, 'invalid_grant', 'client_id does not match the refresh token.');
      // Same revocation check as the authorization_code grant above — a
      // revoked client's refresh token must not mint a fresh access token.
      const client = await prisma.mcpClient.findUnique({ where: { clientId: claims.cid, kind: 'OAUTH' } });
      if (!client) return tokenError(c, 'invalid_grant', 'This client has been revoked.');
      // The binding survives a refresh unchanged, and a refresh token whose
      // uid no longer matches the client's bound user is dead (ADR-0012).
      if (client.userId === null || client.userId !== claims.uid) {
        return tokenError(c, 'invalid_grant', 'This client is not bound to the token user.');
      }

      // Rotated, not reused: a fresh refresh token on every use, same as the
      // access token — neither artefact is ever handed back unchanged.
      const access_token = issueAccessToken({ cid: claims.cid, uid: claims.uid, scope: claims.scope }, secret);
      const refresh_token = issueRefreshToken({ cid: claims.cid, uid: claims.uid, scope: claims.scope }, secret);
      await bumpLastUsed(claims.cid);
      const tokens = OAuthTokensSchema.parse({
        access_token,
        token_type: 'Bearer',
        expires_in: ACCESS_TTL,
        scope: claims.scope.join(' '),
        refresh_token,
      });
      return c.json(tokens, 200, NO_STORE_HEADERS);
    }

    return tokenError(c, 'unsupported_grant_type', `Unsupported grant_type: ${grantType || '(missing)'}.`);
  });
}
